# see: https://docs.docker.com/compose/

version: '3.7'

services:
  
  mssql:
    image: microsoft/mssql-server-linux
    env_file: ./sql.env
    ports: 
      - 1433:1433
    volumes:
      - northwindvolume:/var/opt/mssql

  northwind-dbup:
    build: 
      context: ../Northwind.Project/NorthWind.Data.Migrations
    depends_on:
      - mssql

  northwind-api:
    build: 
      context: ../Northwind.Project
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mssql

  calc-service:
    build: 
      context: ../Calc.Service.Project
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  
  gateway: 
    build: 
      context: ../OcelotGateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  frontend:
    build: 
      context: ../Frontend

  proxy:
    build: 
      context: ../Proxy
    ports:
      - 5060:80

volumes:
  northwindvolume:
    external:
      name: northwind-shared-volume